name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # 1️⃣ Checkout the repository
    - uses: actions/checkout@v4

    # 2️⃣ Set up Java (use Java 17 if your project requires it; else keep 1.8)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin

    # 3️⃣ Ensure Gradle wrapper is executable
    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    # 4️⃣ Cache Gradle dependencies to speed up workflow
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/
        key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    # 5️⃣ Build the project using the Gradle wrapper
    - name: Build with Gradle
      run: ./gradlew build
